### ISSUE TITLE
Renamed Scratch variables conflict

### ISSUE THREAD

**Issue by sfederici** [djsrv/snapinator#2]
I renamed several variables in the Scratch project https://scratch.mit.edu/projects/378349974. For example, I renamed "Dead" to "Deceduti". The Scratch project works fine. After translating the project to Snap, the Snap project ([https://snap.berkeley.edu/snapsource/snap.html#present:Username=s_federici&ProjectName=diffusione%20coronavirus-it-3]) has both the original variables, e.g. "Dead", and the ones with the new names, e.g. "Deceduti", in the Variables category. The variables' names in the scripts are the original ones, e.g. "Dead".

**Comment by djsrv** [comment]
I suspect this has something to do with how Scratch 3.0 refers to a variable by an ID instead of its name. I'll look into it...

**Comment by djsrv** [comment]
This should be fixed by d4ca5b7.

**Comment by sfederici** [comment]
Now there doesn't seem to be conflit. But unfortunately the project doesn't work yet in snap (I'll investigate on it). In the meantime I noticed that the variables shown on the Stage have different positions than Scratch's (there were horizontal in the top and bottom area of the Stage) and the slider display is not visible for the bottom variables when opened in Snap.

**Comment by djsrv** [comment]
Yes, I have yet to implement watcher conversion, so Snap! is creating new watchers for the variables. Last I checked, Scratch 3.0 itself didn't bother loading watchers from Scratch 1.4 projects, so it's not a high priority, but I'll get to it.
